(class (Plant:Animation height)
    (define parts ["\\" "/"])
    (define a [])
    (define b [])
    (while (> height 0)
        (define i (% height parts.length))
        (define j (% (+ 1 height) parts.length))
        (a.push parts[i])
        (b.push parts[j])
        (set! height (- height 1)))

    (set! a (a.join "\n"))
    (set! b (b.join "\n"))
    (base 10 (* 5.5 a.length) {"10px Consolas #00ff00":[a b]} 2000))

(class (Brian:BoardObject)
    (base 100 100 (new Animation 40 25 {"22px Consolas #c0c0c0":["><>" "-<>"]} 1000))
    (set! this.lastBubble 0)
    (method (update dt)
        (BoardObject.prototype.update.call this dt)
        (set! this.dy (+ (* G dt) this.dy))
        (set! this.dx (* 0.99 this.dx))
        (set! this.dy (* 0.99 this.dy))
        
        (set! this.lastBubble (+ this.lastBubble dt))
        (when (> this.lastBubble 2000)
            (set! this.lastBubble 0))
        (define ret [])
        (when (= this.lastBubble 0)
            (ret.push (new Bubble this.x this.y)))
        ret))

(class (Bubble:BoardObject x y)
    (base x y (new Animation 10 10 {"10px Consolas #0000ff":["." "o" "O"]} 3000 true))
    (set! this.dy -0.01))